version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obview_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/obview
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=obview
      - POSTGRES_PORT=5432
      - SESSION_SECRET=${SESSION_SECRET:-obview-default-session-secret}
    volumes:
      - uploads:/app/uploads
    networks:
      - obview_network

  db:
    image: postgres:16-alpine
    container_name: obview_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=obview
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - obview_network

volumes:
  uploads:
  postgres_data:

networks:
  obview_network:
    driver: bridge