// Resumable, chunked upload server using the tus protocol.
//
// Why tus?
//   - Slow connections were silently failing on single-shot 50GB POSTs.
//     tus uploads in small chunks, retries individual chunks, and resumes
//     across reloads / network drops, fixing the entire class of "upload
//     died at 80%" complaints.
//   - The HTTP layer is per-chunk, so reverse-proxy / Node timeouts can no
//     longer kill an in-flight large upload.
//
// Multipart (parallel) mode:
//   For large files on high-RTT WAN paths, single-flow TCP throughput is
//   capped by `window/RTT` and is often further rate-limited by middleboxes
//   (DPI, carrier-grade NAT, CG-shaping). We bypass that ceiling by having
//   the client split a file into N slices and upload each as its own tus
//   upload in parallel — each slice gets its own TCP connection and its
//   own congestion window. The N tus uploads share a `partOf` group id in
//   their metadata; on finish, each part is moved into a per-group dir
//   instead of becoming a file. The client then calls the finalize
//   endpoint, which concatenates the parts into the final file and runs
//   the existing post-upload pipeline (DB row + video processing +
//   transcription) exactly as the single-stream path does.
//
// Auth model:
//   The Express layer (see routes.ts) wraps every /api/uploads/tus* request
//   with `isAuthenticated` and stamps the authenticated user id onto a
//   trusted, server-only request header. This module's hooks read that
//   header and ALSO bind the uploader to the upload at create time, so a
//   second user who somehow learns the upload URL still cannot continue or
//   finalize the upload — see `onIncomingRequest` below. The multipart
//   finalize/cancel endpoints re-validate the same way against the
//   per-group manifest written at part-finish time.

import path from "path";
import fs from "fs";
import { Server as TusServer } from "@tus/server";
import { FileStore } from "@tus/file-store";
import { storage } from "./storage";

export const TUS_USER_HEADER = "x-internal-user-id";

// Group ids are generated by the client (random base36-ish). Keep the
// charset narrow so we can safely use the value as a directory name and
// reject obvious path-traversal attempts at the boundary.
const GROUP_ID_RE = /^[A-Za-z0-9_-]{8,64}$/;

// Hard upper bound on parts per multipart upload. The client caps at 8;
// the server cap is intentionally a little higher so a future client
// bump doesn't require a server change, but is still small enough to
// keep manifest/finalize logic trivially bounded.
const MAX_PART_COUNT = 16;

// A finalize lock older than this is treated as stale (the process
// holding it presumably crashed). Finalize takes seconds-to-minutes
// for a multi-GB concat over local disk; an hour is comfortably
// beyond that for any realistic single upload.
const STALE_LOCK_MS = 60 * 60 * 1000;

// Fired AFTER a tus upload becomes a new version (version > 1) of an
// existing file. The route layer uses this to send the directed-review
// "new version" email if the prior latest version had an open change
// request. Optional — older callers that don't wire it up still work.
export type OnVersionResponse = (args: {
  file: any;
  priorRequesterId: number | null;
  priorRequesterEmail: string | null;
  actorUserId: number;
}) => void;

export interface CreateTusServerOptions {
  uploadsDir: string;        // final on-disk destination for completed uploads
  tusDataDir: string;        // working directory tus uses while chunks stream in
  partsDir: string;          // working directory holding completed parts of in-progress multipart uploads
  maxFileSize?: number;
  onProcessVideo: (file: any, processingId: number) => void;
  onTranscribe: (args: { fileId: number; inputPath: string; fileType: string }) => void;
  onVersionResponse?: OnVersionResponse;
}

export class HttpError extends Error {
  constructor(public status: number, message: string) {
    super(message);
  }
}

interface MultipartManifest {
  uploaderId: number;
  projectId: number;
  partCount: number;
  totalSize: number;
  filename: string;
  customFilename?: string;
  filetype: string;
}

function readUserIdFromTusReq(req: any): number | null {
  // srvx wraps the node request; the trusted header set by the Express
  // middleware lives on the underlying node IncomingMessage.
  const node = req?.runtime?.node?.req || req?.node?.req;
  const headerVal =
    (node?.headers?.[TUS_USER_HEADER] as string | undefined) ||
    (req?.headers?.get?.(TUS_USER_HEADER) as string | undefined);
  const n = Number(headerVal);
  return Number.isFinite(n) && n > 0 ? n : null;
}

async function userCanEditProject(userId: number, projectId: number): Promise<boolean> {
  const user = await storage.getUser(userId);
  if (!user) return false;
  if (user.role === "admin") return true;
  const pu = await storage.getProjectUser(projectId, userId);
  if (pu && (pu.role === "editor" || pu.role === "admin")) return true;
  // Site editors get edit access to any project in a global folder.
  // Mirrors `userHasProjectEditAccess` in server/routes.ts — without
  // this branch, the chunked uploader rejects editors who can edit
  // every other surface of the same project.
  if (user.role === "editor") {
    const project = await storage.getProject(projectId);
    if (project?.folderId != null) {
      const folder = await storage.getFolder(project.folderId);
      if (folder?.isGlobal) return true;
    }
  }
  return false;
}

function safeGroupDir(partsDir: string, groupId: string): string {
  if (!GROUP_ID_RE.test(groupId)) {
    throw new HttpError(400, "Invalid groupId");
  }
  const base = path.resolve(partsDir);
  const groupDir = path.resolve(base, groupId);
  if (!groupDir.startsWith(base + path.sep)) {
    throw new HttpError(400, "Invalid groupId");
  }
  return groupDir;
}

export function createTusServer(opts: CreateTusServerOptions): TusServer {
  fs.mkdirSync(opts.tusDataDir, { recursive: true });
  fs.mkdirSync(opts.uploadsDir, { recursive: true });
  fs.mkdirSync(opts.partsDir, { recursive: true });

  const datastore = new FileStore({ directory: opts.tusDataDir });

  // Per-upload diagnostics. We log once per PATCH so a stalled upload
  // leaves a clear breadcrumb trail in `docker compose logs app` instead
  // of being silently invisible. Throttled to one line per chunk so the
  // log isn't drowned by hundreds of entries per file.
  const lastLogged = new Map<string, number>();

  return new TusServer({
    path: "/api/uploads/tus",
    datastore,
    maxSize: opts.maxFileSize ?? 50 * 1024 * 1024 * 1024, // 50 GB
    respectForwardedHeaders: true,

    async onResponseError(_req, err: any) {
      console.error(
        `[tus] response error status=${err?.status_code ?? "?"} body=${
          typeof err?.body === "string" ? err.body : JSON.stringify(err?.body ?? err?.message ?? err)
        }`,
      );
      return undefined;
    },

    // Re-check authorization on EVERY request that touches an existing
    // upload (HEAD / PATCH / DELETE / final POST). Without this an
    // attacker who steals an authenticated session and an upload URL
    // could resume or terminate someone else's upload, or finalize it
    // into a project they don't have edit access to. By binding the
    // uploader id and target project to the upload at create time and
    // re-validating both here, an upload URL is only useful to the
    // user who created it, for the project it was created for.
    async onIncomingRequest(req, uploadId) {
      if (!uploadId) return; // POST creation goes through onUploadCreate.
      const currentUserId = readUserIdFromTusReq(req);
      if (!currentUserId) {
        throw { status_code: 401, body: "Unauthorized" };
      }
      let upload;
      try {
        upload = await datastore.getUpload(uploadId);
      } catch {
        // Let tus produce its standard 404 for unknown ids.
        return;
      }
      const meta = upload.metadata || {};
      const ownerId = Number(meta.uploaderId);
      const projectId = Number(meta.projectId);
      if (!Number.isFinite(ownerId) || ownerId !== currentUserId) {
        throw { status_code: 403, body: "Forbidden" };
      }
      if (!Number.isFinite(projectId) || !(await userCanEditProject(currentUserId, projectId))) {
        throw { status_code: 403, body: "Insufficient permissions" };
      }

      // Throttled progress log: one line per upload at most every 10s,
      // so a stalled or slow upload is observable from docker logs
      // without flooding them on healthy fast uploads.
      const now = Date.now();
      const last = lastLogged.get(uploadId) || 0;
      if (now - last > 10_000) {
        lastLogged.set(uploadId, now);
        const offset = upload.offset ?? 0;
        const size = upload.size ?? 0;
        const pct = size > 0 ? ((offset / size) * 100).toFixed(1) : "?";
        const fname = meta.filename || meta.customFilename || "(unnamed)";
        const partSuffix = meta.partOf ? ` part=${meta.partIndex}/${meta.partCount}` : "";
        console.log(
          `[tus] ${req.method} ${uploadId.slice(0, 8)} ${fname} ` +
            `offset=${offset} size=${size} (${pct}%) user=${currentUserId}${partSuffix}`,
        );
      }
    },

    // Validate that the uploader is authenticated AND has edit rights to
    // the target project before we accept a single byte. We also stamp
    // the server-trusted uploader id onto the upload's metadata so
    // `onIncomingRequest` can re-validate ownership on every later
    // chunk without trusting anything from the wire.
    async onUploadCreate(req, upload) {
      const meta = upload.metadata || {};
      const projectIdStr = meta.projectId;
      if (!projectIdStr || !/^\d+$/.test(projectIdStr)) {
        throw { status_code: 400, body: "projectId metadata required" };
      }
      const userId = readUserIdFromTusReq(req);
      if (!userId) throw { status_code: 401, body: "Unauthorized" };

      const projectId = Number(projectIdStr);
      const project = await storage.getProject(projectId);
      if (!project) throw { status_code: 404, body: "Project not found" };

      if (!(await userCanEditProject(userId, projectId))) {
        throw { status_code: 403, body: "Insufficient permissions" };
      }

      // Multipart pre-validation: catch malformed group metadata at
      // creation time so we don't wastefully accept an entire part only
      // to reject it on finish.
      if (meta.partOf != null) {
        if (typeof meta.partOf !== "string" || !GROUP_ID_RE.test(meta.partOf)) {
          throw { status_code: 400, body: "Invalid partOf groupId" };
        }
        const partIndex = Number(meta.partIndex);
        const partCount = Number(meta.partCount);
        const totalSize = Number(meta.totalSize);
        if (
          !Number.isFinite(partIndex) || partIndex < 0 || partIndex >= partCount ||
          !Number.isFinite(partCount) || partCount < 2 || partCount > MAX_PART_COUNT ||
          !Number.isFinite(totalSize) || totalSize <= 0
        ) {
          throw { status_code: 400, body: "Invalid part metadata" };
        }
      }

      return {
        metadata: {
          ...meta,
          uploaderId: String(userId),
        },
      };
    },

    // Move the assembled file out of the tus working dir into the canonical
    // uploads directory, create the DB row, log the activity and kick off
    // the existing post-upload pipeline (video processing + transcription).
    // The response body returned here is delivered to tus-js-client via its
    // `onAfterResponse` hook so the UI can immediately reflect the new file.
    async onUploadFinish(req, upload) {
      const meta = upload.metadata || {};
      const projectId = Number(meta.projectId);
      const storedUploaderId = Number(meta.uploaderId);
      const currentUserId = readUserIdFromTusReq(req);
      // Defense in depth: even though onIncomingRequest already checked,
      // refuse to commit if the IDs don't line up.
      if (!currentUserId || currentUserId !== storedUploaderId) {
        throw { status_code: 403, body: "Forbidden" };
      }
      if (!(await userCanEditProject(currentUserId, projectId))) {
        throw { status_code: 403, body: "Insufficient permissions" };
      }

      const tusPath = path.join(opts.tusDataDir, upload.id);

      // Multipart branch: this upload is one slice of a larger file.
      // Move it into the per-group directory and write the shared
      // manifest (idempotent — every part writes the same manifest, but
      // only the first wins to avoid torn reads). The actual file row
      // and post-upload pipeline run in the finalize endpoint after all
      // parts have arrived.
      if (meta.partOf) {
        const partOf = String(meta.partOf);
        const partIndex = Number(meta.partIndex);
        const partCount = Number(meta.partCount);
        const totalSize = Number(meta.totalSize);
        // onUploadCreate already validated; re-check defensively.
        if (
          !GROUP_ID_RE.test(partOf) ||
          !Number.isFinite(partIndex) || partIndex < 0 || partIndex >= partCount ||
          !Number.isFinite(partCount) || partCount < 2 || partCount > MAX_PART_COUNT ||
          !Number.isFinite(totalSize) || totalSize <= 0
        ) {
          throw { status_code: 400, body: "Invalid part metadata" };
        }
        const groupDir = path.join(opts.partsDir, partOf);
        await fs.promises.mkdir(groupDir, { recursive: true });
        const manifestPath = path.join(groupDir, "manifest.json");
        const incomingManifest: MultipartManifest = {
          uploaderId: currentUserId,
          projectId,
          partCount,
          totalSize,
          filename: meta.filename || `upload-${upload.id}`,
          customFilename: meta.customFilename ?? undefined,
          filetype: meta.filetype || "application/octet-stream",
        };

        // Two parts of the same group MUST agree on every manifest field.
        // Without this check, an attacker (or a buggy client) who knows or
        // guesses an in-progress groupId could write parts under different
        // identities/sizes and corrupt the assembled file. The server is
        // the source of truth: if a manifest already exists, every later
        // part must match it exactly or we reject the part.
        let existingManifest: MultipartManifest | null = null;
        try {
          existingManifest = JSON.parse(
            await fs.promises.readFile(manifestPath, "utf8"),
          ) as MultipartManifest;
        } catch (e: any) {
          if (e?.code !== "ENOENT") throw e;
        }
        if (existingManifest) {
          if (
            existingManifest.uploaderId !== incomingManifest.uploaderId ||
            existingManifest.projectId !== incomingManifest.projectId ||
            existingManifest.partCount !== incomingManifest.partCount ||
            existingManifest.totalSize !== incomingManifest.totalSize ||
            existingManifest.filename !== incomingManifest.filename ||
            (existingManifest.customFilename ?? null) !== (incomingManifest.customFilename ?? null) ||
            existingManifest.filetype !== incomingManifest.filetype
          ) {
            throw { status_code: 409, body: "Part metadata does not match upload group manifest" };
          }
        } else {
          // First part to land writes the manifest. `wx` makes this race
          // resilient: if a sibling beat us to it, our write fails with
          // EEXIST and we re-read & re-validate against theirs.
          try {
            await fs.promises.writeFile(manifestPath, JSON.stringify(incomingManifest), { flag: "wx" });
          } catch (e: any) {
            if (e?.code !== "EEXIST") throw e;
            const raceManifest = JSON.parse(
              await fs.promises.readFile(manifestPath, "utf8"),
            ) as MultipartManifest;
            if (
              raceManifest.uploaderId !== incomingManifest.uploaderId ||
              raceManifest.projectId !== incomingManifest.projectId ||
              raceManifest.partCount !== incomingManifest.partCount ||
              raceManifest.totalSize !== incomingManifest.totalSize ||
              raceManifest.filename !== incomingManifest.filename ||
              (raceManifest.customFilename ?? null) !== (incomingManifest.customFilename ?? null) ||
              raceManifest.filetype !== incomingManifest.filetype
            ) {
              throw { status_code: 409, body: "Part metadata does not match upload group manifest" };
            }
          }
        }

        // Refuse to overwrite an already-landed part. A retry that races
        // with the prior attempt is the only legitimate trigger and is
        // safe because tus only fires onUploadFinish on a fully-assembled
        // upload of the agreed size — but treating it as an error
        // surfaces accidental client-side bugs (e.g. sending the same
        // partIndex twice with different content) instead of silently
        // overwriting one with the other.
        const partDest = path.join(groupDir, String(partIndex));
        try {
          await fs.promises.link(tusPath, partDest);
          await fs.promises.unlink(tusPath).catch(() => {});
        } catch (e: any) {
          if (e?.code === "EEXIST") {
            // Idempotent retry: same part already on disk. Drop the new
            // tus blob; keep the existing one. We don't size-compare
            // here because tus already enforces upload.size at the
            // protocol level on the assembled upload.
            await fs.promises.unlink(tusPath).catch(() => {});
          } else if (e?.code === "EXDEV" || e?.code === "EPERM") {
            // Hard link not supported across the boundary; fall back to
            // rename, which is also atomic on POSIX within the same fs.
            try {
              await fs.promises.rename(tusPath, partDest);
            } catch (e2: any) {
              if (e2?.code === "EXDEV") {
                await fs.promises.copyFile(tusPath, partDest, fs.constants.COPYFILE_EXCL);
                await fs.promises.unlink(tusPath);
              } else if (e2?.code === "EEXIST") {
                await fs.promises.unlink(tusPath).catch(() => {});
              } else {
                throw e2;
              }
            }
          } else {
            throw e;
          }
        }
        await fs.promises.unlink(`${tusPath}.json`).catch(() => {});

        return {
          status_code: 200,
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            part: true,
            groupId: partOf,
            partIndex,
            partCount,
          }),
        };
      }

      // Single-stream (default) path — unchanged.
      const filename = meta.customFilename || meta.filename || `upload-${upload.id}`;
      const mimetype = meta.filetype || "application/octet-stream";

      const ext = path.extname(filename) || "";
      const uniqueName = `${Date.now()}-${Math.round(Math.random() * 1e9)}${ext}`;
      const finalPath = path.join(opts.uploadsDir, uniqueName);

      try {
        await fs.promises.rename(tusPath, finalPath);
      } catch (e: any) {
        // Cross-device fallback (e.g. uploads/.tus and uploads/ on different
        // mounts) — copy then remove so renames stay free where possible.
        if (e?.code === "EXDEV") {
          await fs.promises.copyFile(tusPath, finalPath);
          await fs.promises.unlink(tusPath);
        } else {
          throw e;
        }
      }

      let fileType = "other";
      if (mimetype.startsWith("video/")) fileType = "video";
      else if (mimetype.startsWith("audio/")) fileType = "audio";
      else if (mimetype.startsWith("image/")) fileType = "image";

      // Versioning. Important ordering rule: insert the new row FIRST,
      // then demote the previously-latest siblings. If we demoted first
      // and the insert failed, the project would be left with no row
      // marked as latest. Concurrent finishes for the same filename are
      // still racy in theory, but each will end up with a unique
      // monotonically-increasing version and a single demotion pass.
      let fileRow: any;
      let existing: any[] = [];
      let similar: any[] = [];
      let priorRequesterId: number | null = null;
      let priorRequesterEmail: string | null = null;
      try {
        existing = await storage.getFilesByProject(projectId);
        similar = existing.filter((f: any) => f.filename === filename);
        const version =
          similar.length > 0
            ? Math.max(...similar.map((f: any) => f.version)) + 1
            : 1;
        // Capture the prior latest version's open change-request target
        // BEFORE we demote them — used after the insert to email the
        // reviewer that the editor responded with a new version. Email
        // is only consulted when there's no FK user (share-link path).
        if (similar.length > 0) {
          const priorLatest = similar.reduce(
            (a: any, b: any) => (a.version > b.version ? a : b),
          );
          priorRequesterId = priorLatest?.requestedChangesById ?? null;
          priorRequesterEmail = priorLatest?.requestedChangesByEmail ?? null;
        }

        fileRow = await storage.createFile({
          filename,
          fileType,
          fileSize: upload.size ?? 0,
          filePath: finalPath,
          projectId,
          uploadedById: currentUserId,
          version,
          isLatestVersion: true,
        });
      } catch (err) {
        // DB insert failed — the moved file would otherwise be orphaned
        // on disk forever. Best-effort cleanup before re-throwing.
        await fs.promises.unlink(finalPath).catch(() => {});
        throw err;
      }

      // Sidecar tus metadata and any older "latest" markers can be
      // cleaned up now that the new row is safely committed. Failures
      // here are non-fatal — the file is already saved and visible.
      await fs.promises.unlink(`${tusPath}.json`).catch(() => {});
      try {
        if (similar.length > 0) {
          await Promise.all(
            similar.map((f: any) =>
              storage.updateFile(f.id, { isLatestVersion: false })
            )
          );
        }
      } catch (err) {
        console.error("[tus] Failed to demote previous file versions:", err);
      }

      try {
        await storage.logActivity({
          action: "upload",
          entityType: "file",
          entityId: fileRow.id,
          userId: currentUserId,
          metadata: {
            projectId,
            filename: fileRow.filename,
            version: fileRow.version,
            source: "tus",
          },
        });

        if (fileType === "video") {
          const processing = await storage.createVideoProcessing({
            fileId: fileRow.id,
            status: "pending",
          });
          opts.onProcessVideo(fileRow, processing.id);
        }
        if (fileType === "video" || fileType === "audio") {
          opts.onTranscribe({
            fileId: fileRow.id,
            inputPath: fileRow.filePath,
            fileType,
          });
        }
        if ((priorRequesterId || priorRequesterEmail) && opts.onVersionResponse) {
          opts.onVersionResponse({
            file: fileRow,
            priorRequesterId,
            priorRequesterEmail,
            actorUserId: currentUserId,
          });
        }
      } catch (err) {
        console.error("[tus] Post-upload pipeline failed:", err);
      }

      return {
        status_code: 200,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(fileRow),
      };
    },
  });
}

export interface MultipartFinalizerOptions {
  uploadsDir: string;
  partsDir: string;
  onProcessVideo: (file: any, processingId: number) => void;
  onTranscribe: (args: { fileId: number; inputPath: string; fileType: string }) => void;
  onVersionResponse?: OnVersionResponse;
}

// Returns an async function that the routes layer calls when the client
// has finished uploading every part of a multipart upload. Concatenates
// the parts into the canonical uploads directory, creates the DB row,
// kicks off the post-upload pipeline, and removes the per-group working
// directory. Throws HttpError with appropriate status codes on auth,
// missing-parts, size-mismatch, and concurrent-finalize conditions.
export function createMultipartFinalizer(opts: MultipartFinalizerOptions) {
  return async function finalize(args: {
    groupId: string;
    currentUserId: number;
  }): Promise<any> {
    const groupDir = safeGroupDir(opts.partsDir, args.groupId);
    const manifestPath = path.join(groupDir, "manifest.json");

    let manifest: MultipartManifest;
    try {
      const raw = await fs.promises.readFile(manifestPath, "utf8");
      manifest = JSON.parse(raw) as MultipartManifest;
    } catch {
      throw new HttpError(404, "Upload group not found");
    }

    if (manifest.uploaderId !== args.currentUserId) {
      throw new HttpError(403, "Forbidden");
    }
    if (!(await userCanEditProject(args.currentUserId, manifest.projectId))) {
      throw new HttpError(403, "Insufficient permissions");
    }

    // Single-finalize lock. mkdir is atomic on POSIX, so a second
    // concurrent finalize for the same group fails with EEXIST and
    // gets a 409 instead of half-merging the parts twice. If we find
    // a stale lock (older than STALE_LOCK_MS — i.e. the prior process
    // crashed mid-finalize), reclaim it.
    const lockDir = path.join(groupDir, ".finalizing");
    try {
      await fs.promises.mkdir(lockDir);
    } catch (e: any) {
      if (e?.code !== "EEXIST") throw e;
      const lockStat = await fs.promises.stat(lockDir).catch(() => null);
      const age = lockStat ? Date.now() - lockStat.mtimeMs : 0;
      if (!lockStat || age < STALE_LOCK_MS) {
        throw new HttpError(409, "Finalize already in progress");
      }
      console.warn(
        `[multipart] Reclaiming stale finalize lock for group ${args.groupId} (age=${Math.round(age / 1000)}s)`,
      );
      // Refresh the lock so concurrent reclaim attempts also see it as
      // young. Best-effort touch — if it fails we still proceed because
      // we already established the lock is stale above.
      const now = new Date();
      await fs.promises.utimes(lockDir, now, now).catch(() => {});
    }

    let finalPath: string | null = null;
    try {
      // Verify every part is present and the bytes line up exactly with
      // what the client claimed. If anything is off we abort before
      // touching the uploads directory or the DB.
      const partPaths: string[] = [];
      let totalBytes = 0;
      for (let i = 0; i < manifest.partCount; i++) {
        const p = path.join(groupDir, String(i));
        const st = await fs.promises.stat(p).catch(() => null);
        if (!st || !st.isFile()) {
          throw new HttpError(409, `Part ${i} not yet uploaded`);
        }
        partPaths.push(p);
        totalBytes += st.size;
      }
      if (totalBytes !== manifest.totalSize) {
        throw new HttpError(
          409,
          `Size mismatch: parts total ${totalBytes} bytes, expected ${manifest.totalSize}`,
        );
      }

      const filename = manifest.customFilename || manifest.filename;
      const ext = path.extname(filename) || "";
      const uniqueName = `${Date.now()}-${Math.round(Math.random() * 1e9)}${ext}`;
      finalPath = path.join(opts.uploadsDir, uniqueName);

      // Concatenate parts in order into the final file. Streaming
      // copy avoids loading any part into memory; multi-GB files are
      // routine here. We pipe each part's read stream into the same
      // write stream with `{ end: false }` so the writable stays open
      // across all parts, then explicitly end it once all parts have
      // been consumed.
      const out = fs.createWriteStream(finalPath);
      const writeErr = new Promise<void>((_, reject) => {
        out.on("error", reject);
      });
      try {
        for (const pp of partPaths) {
          await Promise.race([
            new Promise<void>((resolve, reject) => {
              const rs = fs.createReadStream(pp);
              rs.on("error", reject);
              rs.on("end", () => resolve());
              rs.pipe(out, { end: false });
            }),
            writeErr,
          ]);
        }
        await new Promise<void>((resolve, reject) => {
          out.end(() => resolve());
          out.on("error", reject);
        });
      } catch (e) {
        out.destroy();
        await fs.promises.unlink(finalPath).catch(() => {});
        finalPath = null;
        throw e;
      }

      const mimetype = manifest.filetype || "application/octet-stream";
      let fileType = "other";
      if (mimetype.startsWith("video/")) fileType = "video";
      else if (mimetype.startsWith("audio/")) fileType = "audio";
      else if (mimetype.startsWith("image/")) fileType = "image";

      const projectId = manifest.projectId;
      let fileRow: any;
      let similar: any[] = [];
      let priorRequesterId: number | null = null;
      let priorRequesterEmail: string | null = null;
      try {
        const existing = await storage.getFilesByProject(projectId);
        similar = existing.filter((f: any) => f.filename === filename);
        const version =
          similar.length > 0
            ? Math.max(...similar.map((f: any) => f.version)) + 1
            : 1;
        if (similar.length > 0) {
          const priorLatest = similar.reduce(
            (a: any, b: any) => (a.version > b.version ? a : b),
          );
          priorRequesterId = priorLatest?.requestedChangesById ?? null;
          priorRequesterEmail = priorLatest?.requestedChangesByEmail ?? null;
        }
        fileRow = await storage.createFile({
          filename,
          fileType,
          fileSize: manifest.totalSize,
          filePath: finalPath,
          projectId,
          uploadedById: args.currentUserId,
          version,
          isLatestVersion: true,
        });
      } catch (err) {
        if (finalPath) await fs.promises.unlink(finalPath).catch(() => {});
        finalPath = null;
        throw err;
      }

      try {
        if (similar.length > 0) {
          await Promise.all(
            similar.map((f: any) =>
              storage.updateFile(f.id, { isLatestVersion: false }),
            ),
          );
        }
      } catch (err) {
        console.error("[multipart] Failed to demote previous file versions:", err);
      }

      try {
        await storage.logActivity({
          action: "upload",
          entityType: "file",
          entityId: fileRow.id,
          userId: args.currentUserId,
          metadata: {
            projectId,
            filename: fileRow.filename,
            version: fileRow.version,
            source: "tus-multipart",
            partCount: manifest.partCount,
          },
        });

        if (fileType === "video") {
          const processing = await storage.createVideoProcessing({
            fileId: fileRow.id,
            status: "pending",
          });
          opts.onProcessVideo(fileRow, processing.id);
        }
        if (fileType === "video" || fileType === "audio") {
          opts.onTranscribe({
            fileId: fileRow.id,
            inputPath: fileRow.filePath,
            fileType,
          });
        }
        if ((priorRequesterId || priorRequesterEmail) && opts.onVersionResponse) {
          opts.onVersionResponse({
            file: fileRow,
            priorRequesterId,
            priorRequesterEmail,
            actorUserId: args.currentUserId,
          });
        }
      } catch (err) {
        console.error("[multipart] Post-upload pipeline failed:", err);
      }

      // Successful finalize: remove the entire per-group working dir
      // (parts + manifest + lock). Best-effort — orphans here are
      // disk waste only, not a correctness issue.
      await fs.promises.rm(groupDir, { recursive: true, force: true }).catch(() => {});
      return fileRow;
    } catch (err) {
      // Release the lock so the client can retry the finalize call
      // (parts on disk are preserved). A truly fatal error will see
      // the client cancel the upload, which deletes the whole groupDir.
      await fs.promises.rm(lockDir, { recursive: true, force: true }).catch(() => {});
      throw err;
    }
  };
}

// Cancel: drop the entire per-group working dir. Used by the client
// when the user explicitly cancels a parallel upload before all parts
// have arrived (or after a finalize failure they don't want to retry).
// Refuses to interrupt an in-progress finalize so we never delete part
// files out from under the concatenation loop. The client should retry
// cancel after a short delay, or the user can wait for finalize to
// complete and then delete the resulting file via the regular UI.
export function createMultipartCanceller(opts: { partsDir: string }) {
  return async function cancel(args: {
    groupId: string;
    currentUserId: number;
  }): Promise<void> {
    const groupDir = safeGroupDir(opts.partsDir, args.groupId);
    const manifestPath = path.join(groupDir, "manifest.json");
    let manifest: MultipartManifest | null = null;
    try {
      manifest = JSON.parse(
        await fs.promises.readFile(manifestPath, "utf8"),
      ) as MultipartManifest;
    } catch {
      // No manifest → nothing to clean (or already gone). Treat as
      // success so client cancel is idempotent.
      return;
    }
    if (manifest.uploaderId !== args.currentUserId) {
      throw new HttpError(403, "Forbidden");
    }
    // Refuse to race finalize. A live finalize lock means the
    // concatenation loop is actively reading the part files; ripping
    // them out from under it would produce a corrupt or truncated
    // final file. A stale lock (process crashed mid-finalize) is
    // reclaimable, so cancel proceeds in that case.
    const lockDir = path.join(groupDir, ".finalizing");
    const lockStat = await fs.promises.stat(lockDir).catch(() => null);
    if (lockStat) {
      const age = Date.now() - lockStat.mtimeMs;
      if (age < STALE_LOCK_MS) {
        throw new HttpError(409, "Finalize in progress; cannot cancel");
      }
      console.warn(
        `[multipart] Cancel proceeding past stale finalize lock for group ${args.groupId} (age=${Math.round(age / 1000)}s)`,
      );
    }
    await fs.promises.rm(groupDir, { recursive: true, force: true }).catch(() => {});
  };
}
